language: go

addons:
  apt_packages:
  - gnome-terminal
  - libgl1-mesa-dev
  - libasound2-dev
  - xorg-dev

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - PATH="$HOME/gopath/bin:$PATH"
  - gnome-terminal -e 'go test ./... -v -covermode=count -coverprofile=cover.out'
  - goveralls -coverprofile cover.out -service=travis-ci -repotoken $TOKEN